import React from 'react';
import { Link } from 'react-router-dom';

const TrendAnalysisCard = ({ analysis }) => {
  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  return (
    <div className="bg-white rounded-lg shadow-sm p-6 border border-ink/10">
      <div className="flex items-start justify-between mb-4">
        <div className="flex-1">
          <h3 className="text-xl font-heading font-bold text-ink mb-2">
            {analysis.sector ? `${analysis.sector} Sector Trends` : 'Overall Market Trends'}
          </h3>
          <p className="text-sm font-body text-ink/60">
            Analysis Date: {formatDate(analysis.analysis_date)}
          </p>
        </div>
        <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-body font-medium bg-teal/10 text-teal">
          {analysis.submission_volume} Proposals
        </span>
      </div>

      {analysis.emerging_technologies && analysis.emerging_technologies.length > 0 && (
        <div className="mb-4">
          <h4 className="text-sm font-body font-medium text-ink mb-2">Emerging Technologies</h4>
          <div className="flex flex-wrap gap-2">
            {analysis.emerging_technologies.map((tech, index) => (
              <span key={index} className="inline-flex items-center px-3 py-1 rounded-full text-xs font-body font-medium bg-gold/10 text-gold">
                {tech}
              </span>
            ))}
          </div>
        </div>
      )}

      {analysis.average_scores && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4 pt-4 border-t border-ink/10">
          {Object.entries(analysis.average_scores).map(([key, value]) => (
            <div key={key}>
              <p className="text-xs font-body text-ink/60 mb-1">
                {key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}
              </p>
              <p className="text-lg font-heading font-bold text-teal">
                {typeof value === 'number' ? value.toFixed(1) : value}
              </p>
            </div>
          ))}
        </div>
      )}

      <div className="mt-4 pt-4 border-t border-ink/10">
        <p className="text-xs font-body text-ink/40">
          Generated by: {analysis.generated_by}
        </p>
      </div>
    </div>
  );
};

export default TrendAnalysisCard;