import React, { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import api, { getErrorMessage } from '../lib/api';

const TrendAnalysesList = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [analyses, setAnalyses] = useState([]);
  const [pagination, setPagination] = useState(null);

  const page = parseInt(searchParams.get('page') || '1', 10);
  const pageSize = 20;

  useEffect(() => {
    fetchAnalyses();
  }, [page]);

  const fetchAnalyses = async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await api.get(`/api/v1/trend-analyses?page=${page}&page_size=${pageSize}`);
      setAnalyses(res.data.analyses || []);
      setPagination(res.data.pagination);
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setLoading(false);
    }
  };

  const handlePageChange = (newPage) => {
    setSearchParams({ page: newPage.toString() });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-cream flex items-center justify-center">
        <div className="animate-pulse text-teal font-heading text-2xl">Loading trend analyses...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-cream p-8">
      <div className="max-w-7xl mx-auto">
        <header className="mb-6">
          <h1 className="font-heading text-4xl text-teal">Trend Analyses</h1>
        </header>

        {error && (
          <div className="bg-burgundy/10 border border-burgundy rounded-lg p-4 mb-6">
            <p className="text-burgundy">{error}</p>
          </div>
        )}

        <div className="space-y-6">
          {analyses.length === 0 ? (
            <div className="bg-white rounded-xl shadow-md p-8 text-center text-ink/60">
              No trend analyses found
            </div>
          ) : (
            analyses.map((a) => (
              <div key={a.id} className="bg-white rounded-xl shadow-md p-6">
                <div className="flex items-start justify-between mb-4">
                  <div>
                    <h3 className="font-heading text-xl text-teal mb-1">
                      {a.sector ? `${a.sector} Sector` : 'Cross-Sector'} Analysis
                    </h3>
                    <p className="text-sm text-ink/60">
                      {new Date(a.analysis_date).toLocaleDateString()} • {a.submission_volume} proposals analyzed
                    </p>
                  </div>
                  <span className="text-xs text-ink/50">Generated by {a.generated_by}</span>
                </div>
                {a.emerging_technologies && a.emerging_technologies.length > 0 && (
                  <div className="mb-4">
                    <h4 className="text-sm font-medium text-ink mb-2">Emerging Technologies:</h4>
                    <div className="flex flex-wrap gap-2">
                      {a.emerging_technologies.map((tech, i) => (
                        <span key={i} className="bg-gold/20 text-gold px-3 py-1 rounded-full text-xs font-medium">
                          {tech}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {a.average_scores && (
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    {Object.entries(a.average_scores).map(([key, val]) => (
                      <div key={key} className="border border-cream rounded-lg p-3">
                        <div className="text-xs text-ink/60 mb-1 capitalize">{key.replace('_', ' ')}</div>
                        <div className="font-heading text-xl text-teal">{val?.toFixed(1) || 'N/A'}</div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))
          )}
        </div>

        {pagination && pagination.total_pages > 1 && (
          <div className="flex items-center justify-center space-x-2 mt-6">
            <button
              onClick={() => handlePageChange(page - 1)}
              disabled={page === 1}
              className="px-4 py-2 rounded-lg bg-white border border-cream disabled:opacity-50 hover:bg-cream transition"
            >
              Previous
            </button>
            <span className="text-ink">
              Page {page} of {pagination.total_pages}
            </span>
            <button
              onClick={() => handlePageChange(page + 1)}
              disabled={page === pagination.total_pages}
              className="px-4 py-2 rounded-lg bg-white border border-cream disabled:opacity-50 hover:bg-cream transition"
            >
              Next
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default TrendAnalysesList;